"""Document parser for PDF, DOCX, TXT, MD, CSV, EPUB files."""
import csv
from pathlib import Path

import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup
import fitz  # PyMuPDF (replaces pdfplumber - consistent with indexer.py)
from docx import Document


VIDEO_EXTENSIONS = {".mp4", ".mov", ".webm", ".avi", ".mkv"}

SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".doc", ".txt", ".md", ".csv", ".epub", ".jpg", ".jpeg", ".png", ".webp"} | VIDEO_EXTENSIONS

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}


def is_image(path: Path) -> bool:
    """Check if a file is a supported image format."""
    return path.suffix.lower() in IMAGE_EXTENSIONS


def is_video(path: Path) -> bool:
    """Check if a file is a supported video format."""
    return path.suffix.lower() in VIDEO_EXTENSIONS


def parse_document(path: Path) -> str:
    """Parse a document and return its text content."""
    ext = path.suffix.lower()

    if ext not in SUPPORTED_EXTENSIONS:
        raise ValueError(f"Unsupported file format: {ext}")

    if ext == ".pdf":
        return _parse_pdf(path)
    elif ext in (".docx", ".doc"):
        return _parse_docx(path)
    elif ext in (".txt", ".md"):
        return path.read_text(encoding="utf-8")
    elif ext == ".csv":
        return _parse_csv(path)
    elif ext == ".epub":
        return _parse_epub(path)

    raise ValueError(f"Unsupported file format: {ext}")


def _parse_pdf(path: Path) -> str:
    """Extract text from PDF using PyMuPDF."""
    doc = fitz.open(str(path))
    pages = []
    for i, page in enumerate(doc):
        text = page.get_text()
        if text.strip():
            pages.append(f"[Seite {i + 1}]\n{text}")
    doc.close()
    return "\n\n".join(pages)


def _parse_docx(path: Path) -> str:
    """Extract text from DOCX file."""
    doc = Document(str(path))
    return "\n\n".join(p.text for p in doc.paragraphs if p.text.strip())


def _parse_csv(path: Path) -> str:
    """Convert CSV rows to readable text."""
    lines = []
    with open(path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            line = ", ".join(f"{k}: {v}" for k, v in row.items() if v)
            lines.append(line)
    return "\n".join(lines)


def _parse_epub(path: Path) -> str:
    """Extract text from EPUB file."""
    book = epub.read_epub(str(path), options={"ignore_ncx": True})
    chapters = []
    chapter_num = 0

    for item in book.get_items_of_type(ebooklib.ITEM_DOCUMENT):
        soup = BeautifulSoup(item.get_content(), "html.parser")
        text = soup.get_text(separator="\n", strip=True)
        if text.strip() and len(text.strip()) > 50:
            chapter_num += 1
            title = item.get_name().rsplit("/", 1)[-1].rsplit(".", 1)[0]
            chapters.append(f"[Kapitel {chapter_num}: {title}]\n{text}")

    return "\n\n".join(chapters)


# Boilerplate patterns to strip from scanned books (Google Books, Internet Archive, etc.)
_BOILERPLATE_MARKERS = [
    "This is a digital copy of a book that was preserved",
    "Google Book Search",
    "digitized by Google",
    "Digitized by Google",
    "Generated by ABC Amber LIT Converter",
    "This book is provided for free by the Internet Archive",
    "Original from",
    "we have taken steps to prevent abuse by commercial parties",
    "Make non-commercial use of the files",
    "Refrain from automated querying",
    "Maintain attribution",
    "Google is proud to partner with libraries",
    "Copyright infringement liability can be quite severe",
]


def _strip_boilerplate(text: str) -> str:
    """Remove common boilerplate text from scanned/digitized books.

    Strips Google Books disclaimers, Internet Archive notices, and similar
    preamble/appendix text that pollutes search results.
    Works by removing lines/paragraphs that contain known marker phrases.
    """
    # Split into paragraphs (double newline separated)
    paragraphs = text.split("\n\n")
    cleaned = []
    skip_until_content = True  # Skip leading boilerplate paragraphs

    for para in paragraphs:
        # Check if this paragraph contains boilerplate
        is_boilerplate = any(marker in para for marker in _BOILERPLATE_MARKERS)

        if is_boilerplate:
            skip_until_content = True
            continue

        # Once we find real content, stop skipping
        if para.strip() and len(para.strip()) > 30:
            skip_until_content = False

        if not skip_until_content:
            cleaned.append(para)

    return "\n\n".join(cleaned)


def chunk_text(text: str, chunk_size: int = 500, overlap: int = 50) -> list[str]:
    """Split text into overlapping chunks by approximate word count.

    Automatically strips known boilerplate (Google Books, Internet Archive)
    before chunking.
    """
    text = _strip_boilerplate(text)
    words = text.split()
    chunks = []
    start = 0

    while start < len(words):
        end = start + chunk_size
        chunk = " ".join(words[start:end])
        if chunk.strip():
            chunks.append(chunk)
        start = end - overlap

    return chunks
